[package]
name = "atomichron"
version = "0.1.0"
edition = "2021"
about = "A CLI time tracking utility"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.15", features = ["derive"] }
